### ISSUE TITLE
Broken: TypeError on click 8.2 (make_metavar missing ctx argument)

### ISSUE THREAD

**Issue by trillium** [pokey/upgrade-knausj#8]
## Problem

`upgrade-knausj` crashes immediately on any invocation (including `--help`) with:

```
TypeError: Parameter.make_metavar() missing 1 required positional argument: 'ctx'
```

## Cause

`pyproject.toml` pins `typer = { extras = ["all"], version = "^0.7.0" }`, which resolves to typer versions that pull in click 8.2. Click 8.2 introduced a breaking change to `Parameter.make_metavar()` — it now requires a `ctx` argument. Typer versions before 0.15.0 don't handle this.

Additionally, the `[all]` extra was removed in newer typer versions (rich is now bundled by default).

## Fix

Upgrade typer to `>=0.15.0` which has native click 8.2 support.

## Reproduction

```bash
# Any of these crash:
pipx install upgrade-knausj
upgrade-knausj --help

# Or with uv:
uv tool run upgrade-knausj --help
```

Tested on Python 3.12 and 3.14, both crash.

## PR

#1 — upgrades typer to `>=0.15.0`, tested working on Python 3.12 and 3.14.
